/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "clavesRPC.h"

bool_t
xdr_paquete_rpc (XDR *xdrs, paquete_rpc *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_write_args (XDR *xdrs, write_args *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->key, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 255))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->V_value2.V_value2_val, (u_int *) &objp->V_value2.V_value2_len, 32,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_paquete_rpc (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_key_arg (XDR *xdrs, key_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->key, 255))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_result_simple (XDR *xdrs, result_simple *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_result_get (XDR *xdrs, result_get *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 255))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->V_value2.V_value2_val, (u_int *) &objp->V_value2.V_value2_len, 32,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_paquete_rpc (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}
