/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "clavesRPC.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
destroy_1(result_simple *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, DESTROY, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_result_simple, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
set_value_1(write_args arg1, result_simple *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, SET_VALUE,
		(xdrproc_t) xdr_write_args, (caddr_t) &arg1,
		(xdrproc_t) xdr_result_simple, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
get_value_1(key_arg arg1, result_get *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, GET_VALUE,
		(xdrproc_t) xdr_key_arg, (caddr_t) &arg1,
		(xdrproc_t) xdr_result_get, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
modify_value_1(write_args arg1, result_simple *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, MODIFY_VALUE,
		(xdrproc_t) xdr_write_args, (caddr_t) &arg1,
		(xdrproc_t) xdr_result_simple, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
delete_key_1(key_arg arg1, result_simple *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, DELETE_KEY,
		(xdrproc_t) xdr_key_arg, (caddr_t) &arg1,
		(xdrproc_t) xdr_result_simple, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
exist_1(key_arg arg1, result_simple *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, EXIST,
		(xdrproc_t) xdr_key_arg, (caddr_t) &arg1,
		(xdrproc_t) xdr_result_simple, (caddr_t) clnt_res,
		TIMEOUT));
}
