/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "clavesRPC.h"


void
claves_prog_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	result_simple result_1;
	enum clnt_stat retval_2;
	result_simple result_2;
	write_args set_value_1_arg1;
	enum clnt_stat retval_3;
	result_get result_3;
	key_arg get_value_1_arg1;
	enum clnt_stat retval_4;
	result_simple result_4;
	write_args modify_value_1_arg1;
	enum clnt_stat retval_5;
	result_simple result_5;
	key_arg delete_key_1_arg1;
	enum clnt_stat retval_6;
	result_simple result_6;
	key_arg exist_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, CLAVES_PROG, CLAVES_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = destroy_1(&result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = set_value_1(set_value_1_arg1, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = get_value_1(get_value_1_arg1, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = modify_value_1(modify_value_1_arg1, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = delete_key_1(delete_key_1_arg1, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = exist_1(exist_1_arg1, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	claves_prog_1 (host);
exit (0);
}
