/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVESRPC_H_RPCGEN
#define _CLAVESRPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct paquete_rpc {
	int x;
	int y;
	int z;
};
typedef struct paquete_rpc paquete_rpc;

struct write_args {
	char *key;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		float *V_value2_val;
	} V_value2;
	paquete_rpc value3;
};
typedef struct write_args write_args;

struct key_arg {
	char *key;
};
typedef struct key_arg key_arg;

struct result_simple {
	int result;
};
typedef struct result_simple result_simple;

struct result_get {
	int result;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		float *V_value2_val;
	} V_value2;
	paquete_rpc value3;
};
typedef struct result_get result_get;

#define CLAVES_PROG 0x20000001
#define CLAVES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define DESTROY 1
extern  enum clnt_stat destroy_1(result_simple *, CLIENT *);
extern  bool_t destroy_1_svc(result_simple *, struct svc_req *);
#define SET_VALUE 2
extern  enum clnt_stat set_value_1(write_args , result_simple *, CLIENT *);
extern  bool_t set_value_1_svc(write_args , result_simple *, struct svc_req *);
#define GET_VALUE 3
extern  enum clnt_stat get_value_1(key_arg , result_get *, CLIENT *);
extern  bool_t get_value_1_svc(key_arg , result_get *, struct svc_req *);
#define MODIFY_VALUE 4
extern  enum clnt_stat modify_value_1(write_args , result_simple *, CLIENT *);
extern  bool_t modify_value_1_svc(write_args , result_simple *, struct svc_req *);
#define DELETE_KEY 5
extern  enum clnt_stat delete_key_1(key_arg , result_simple *, CLIENT *);
extern  bool_t delete_key_1_svc(key_arg , result_simple *, struct svc_req *);
#define EXIST 6
extern  enum clnt_stat exist_1(key_arg , result_simple *, CLIENT *);
extern  bool_t exist_1_svc(key_arg , result_simple *, struct svc_req *);
extern int claves_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DESTROY 1
extern  enum clnt_stat destroy_1();
extern  bool_t destroy_1_svc();
#define SET_VALUE 2
extern  enum clnt_stat set_value_1();
extern  bool_t set_value_1_svc();
#define GET_VALUE 3
extern  enum clnt_stat get_value_1();
extern  bool_t get_value_1_svc();
#define MODIFY_VALUE 4
extern  enum clnt_stat modify_value_1();
extern  bool_t modify_value_1_svc();
#define DELETE_KEY 5
extern  enum clnt_stat delete_key_1();
extern  bool_t delete_key_1_svc();
#define EXIST 6
extern  enum clnt_stat exist_1();
extern  bool_t exist_1_svc();
extern int claves_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_paquete_rpc (XDR *, paquete_rpc*);
extern  bool_t xdr_write_args (XDR *, write_args*);
extern  bool_t xdr_key_arg (XDR *, key_arg*);
extern  bool_t xdr_result_simple (XDR *, result_simple*);
extern  bool_t xdr_result_get (XDR *, result_get*);

#else /* K&R C */
extern bool_t xdr_paquete_rpc ();
extern bool_t xdr_write_args ();
extern bool_t xdr_key_arg ();
extern bool_t xdr_result_simple ();
extern bool_t xdr_result_get ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVESRPC_H_RPCGEN */
